---
name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This is needed if we are using github enterprise.
permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: [self-hosted, "${{ matrix.os }}", baremetal]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set cargo
        uses: dtolnay/rust-toolchain@1.79.0

      - name: Clear rust cache
        run: |
          cargo cache -r all

      - name: Set PROTOC environment variable in order to build
        run: echo "PROTOC=/usr/bin/protoc" >> $GITHUB_ENV

      - name: Cargo fmt
        if: startsWith(github.ref, 'refs/tags/') != true
        run: cargo +nightly fmt --all -- --check

      - name: Cargo clippy
        if: startsWith(github.ref, 'refs/tags/') != true
        run: cargo clippy --workspace --all-targets --tests
      
      - name: Cargo check the entire project
        if: startsWith(github.ref, 'refs/tags/') != true
        run: cargo check --all-targets --tests --all-features

      - name: Cargo deny check advisories
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check advisories