[workspace]
members = [
    "crates/yellowstone-fumarole-client",
    "examples/rust",
]
resolver = "2"

[workspace.package]
authors = ["Triton One"]
version = "0.1.1+solana.2.1.11"
edition = "2021"
homepage = "https://triton.one"
repository = "https://github.com/rpcpool/yellowstone-fumarole"
license = "AGPL-3.0"
keywords = ["solana"]
publish = false


[workspace.dependencies]
clap = "4.5.7"
http = "1.2.0"
hyper = "1.3.1"
prost = "0.13.0"
protobuf-src = "1.1.0"
serde = "1.0.203"
serde_with = "3.8.1"
serde_yaml = "0.9.34"
solana-sdk = "=2.1.11"
thiserror = "1.0.61"
tokio = "1.38.0"
tokio-stream = "0.1.11"
tonic = "0.12.3"
tonic-build = "0.12.3"
tower = "0.5.2"
yellowstone-fumarole-client = { path = "crates/yellowstone-fumarole-client" }
yellowstone-grpc-client = "5.0.0"
yellowstone-grpc-proto = "5.0.0"
spl-token-2022 = "7.0.0"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"