[package]
name = "yellowstone-fumarole-napi"
version = "0.1.0"
edition = "2021"
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["async", "tokio_rt", "napi6"] }
napi-derive = "2"
yellowstone-fumarole-client = { path = "../yellowstone-fumarole-client" }
yellowstone-grpc-proto = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde_yaml = { workspace = true }

[build-dependencies]
napi-build = "2"

[lints]
workspace = true
