/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A client connected to a Fumarole service. */
export declare class FumaroleClient {
  /** Connect to a Fumarole service. */
  static connect(config: FumaroleConfigOptions): Promise<FumaroleClient>
  /** Returns the service version as a protobuf-encoded `VersionResponse`. */
  version(): Promise<Buffer>
  /**
   * Subscribe to a stream of updates using default config.
   *
   * `request` must be a protobuf-encoded `geyser.SubscribeRequest`.
   */
  subscribe(subscriberName: string, request: Buffer): Promise<FumaroleSubscription>
  /**
   * Subscribe to a stream of updates with custom tuning.
   *
   * `request` must be a protobuf-encoded `geyser.SubscribeRequest`.
   */
  subscribeWithConfig(subscriberName: string, request: Buffer, config: FumaroleSubscribeConfigOptions): Promise<FumaroleSubscription>
  /**
   * Returns a protobuf-encoded `ListConsumerGroupsResponse`.
   *
   * `request` must be a protobuf-encoded `ListConsumerGroupsRequest`.
   */
  listConsumerGroups(request: Buffer): Promise<Buffer>
  /**
   * Returns a protobuf-encoded `ConsumerGroupInfo`.
   *
   * `request` must be a protobuf-encoded `GetConsumerGroupInfoRequest`.
   */
  getConsumerGroupInfo(request: Buffer): Promise<Buffer>
  /**
   * Returns a protobuf-encoded `DeleteConsumerGroupResponse`.
   *
   * `request` must be a protobuf-encoded `DeleteConsumerGroupRequest`.
   */
  deleteConsumerGroup(request: Buffer): Promise<Buffer>
  /**
   * Returns a protobuf-encoded `CreateConsumerGroupResponse`.
   *
   * `request` must be a protobuf-encoded `CreateConsumerGroupRequest`.
   */
  createConsumerGroup(request: Buffer): Promise<Buffer>
  /**
   * Returns a protobuf-encoded `GetChainTipResponse`.
   *
   * `request` must be a protobuf-encoded `GetChainTipRequest`.
   */
  getChainTip(request: Buffer): Promise<Buffer>
  /** Returns a protobuf-encoded `GetSlotRangeResponse`. */
  getSlotRange(): Promise<Buffer>
}

/**
 * An active Fumarole subscription.
 *
 * Call [`next`] in a loop to receive events, or use `for await` on the
 * async iterator. Send [`geyser.SubscribeRequest`] updates via [`send`] to
 * change filters while the stream is live.
 */
export declare class FumaroleSubscription {
  /** Returns the next event from the subscription, or `null` when the stream ends. */
  next(): Promise<FumaroleEvent | null>
  /**
   * Update the active subscription filters.
   *
   * `request` must be a protobuf-encoded `geyser.SubscribeRequest`.
   */
  send(request: Buffer): Promise<void>
}

/** Connection configuration for a Fumarole client. */
export interface FumaroleConfigOptions {
  endpoint: string
  xToken?: string
  /** Maximum protobuf message size in bytes (default: 512 MB). */
  maxDecodingMessageSizeBytes?: number
}

/** A single event yielded by a [`FumaroleSubscription`]. */
export interface FumaroleEvent {
  slot: bigint
  /** `true` when the slot has finished streaming (no more data for this slot). */
  isSlotEnded: boolean
  /**
   * Protobuf-encoded `geyser.SubscribeUpdate` bytes.
   * Present only when `is_slot_ended` is `false`.
   */
  update?: Buffer
}

/** Tuning options for a [`FumaroleSubscription`]. */
export interface FumaroleSubscribeConfigOptions {
  /** Number of parallel data-plane TCP connections (default: 1). */
  numDataPlaneTcpConnections?: number
  /** Max concurrent downloads per TCP connection (default: 2). */
  concurrentDownloadLimitPerTcp?: number
  /** Offset commit interval in milliseconds (default: 10 000). */
  commitIntervalMs?: number
  /** Max consecutive failed slot downloads before the session fails (default: 3). */
  maxFailedSlotDownloadAttempt?: number
  /** GC tick interval (default: 100). */
  gcInterval?: number
  /** How many slots of dedup memory to keep (default: 1 000). */
  slotMemoryRetention?: number
  /** Disable offset commits entirely. */
  noCommit?: boolean
  /** Automatically commit progress after each event. */
  autoCommit?: boolean
}
