# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import yellowstone_api.fumarole_pb2 as fumarole__pb2
import yellowstone_api.geyser_pb2 as geyser__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fumarole_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FumaroleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAvailableCommitmentLevels = channel.unary_unary(
                '/fumarole.Fumarole/ListAvailableCommitmentLevels',
                request_serializer=fumarole__pb2.ListAvailableCommitmentLevelsRequest.SerializeToString,
                response_deserializer=fumarole__pb2.ListAvailableCommitmentLevelsResponse.FromString,
                _registered_method=True)
        self.GetConsumerGroupInfo = channel.unary_unary(
                '/fumarole.Fumarole/GetConsumerGroupInfo',
                request_serializer=fumarole__pb2.GetConsumerGroupInfoRequest.SerializeToString,
                response_deserializer=fumarole__pb2.ConsumerGroupInfo.FromString,
                _registered_method=True)
        self.ListConsumerGroups = channel.unary_unary(
                '/fumarole.Fumarole/ListConsumerGroups',
                request_serializer=fumarole__pb2.ListConsumerGroupsRequest.SerializeToString,
                response_deserializer=fumarole__pb2.ListConsumerGroupsResponse.FromString,
                _registered_method=True)
        self.DeleteConsumerGroup = channel.unary_unary(
                '/fumarole.Fumarole/DeleteConsumerGroup',
                request_serializer=fumarole__pb2.DeleteConsumerGroupRequest.SerializeToString,
                response_deserializer=fumarole__pb2.DeleteConsumerGroupResponse.FromString,
                _registered_method=True)
        self.CreateStaticConsumerGroup = channel.unary_unary(
                '/fumarole.Fumarole/CreateStaticConsumerGroup',
                request_serializer=fumarole__pb2.CreateStaticConsumerGroupRequest.SerializeToString,
                response_deserializer=fumarole__pb2.CreateStaticConsumerGroupResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.stream_stream(
                '/fumarole.Fumarole/Subscribe',
                request_serializer=fumarole__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=geyser__pb2.SubscribeUpdate.FromString,
                _registered_method=True)
        self.GetSlotLagInfo = channel.unary_unary(
                '/fumarole.Fumarole/GetSlotLagInfo',
                request_serializer=fumarole__pb2.GetSlotLagInfoRequest.SerializeToString,
                response_deserializer=fumarole__pb2.GetSlotLagInfoResponse.FromString,
                _registered_method=True)


class FumaroleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAvailableCommitmentLevels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsumerGroupInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConsumerGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConsumerGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStaticConsumerGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSlotLagInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FumaroleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAvailableCommitmentLevels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableCommitmentLevels,
                    request_deserializer=fumarole__pb2.ListAvailableCommitmentLevelsRequest.FromString,
                    response_serializer=fumarole__pb2.ListAvailableCommitmentLevelsResponse.SerializeToString,
            ),
            'GetConsumerGroupInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsumerGroupInfo,
                    request_deserializer=fumarole__pb2.GetConsumerGroupInfoRequest.FromString,
                    response_serializer=fumarole__pb2.ConsumerGroupInfo.SerializeToString,
            ),
            'ListConsumerGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConsumerGroups,
                    request_deserializer=fumarole__pb2.ListConsumerGroupsRequest.FromString,
                    response_serializer=fumarole__pb2.ListConsumerGroupsResponse.SerializeToString,
            ),
            'DeleteConsumerGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConsumerGroup,
                    request_deserializer=fumarole__pb2.DeleteConsumerGroupRequest.FromString,
                    response_serializer=fumarole__pb2.DeleteConsumerGroupResponse.SerializeToString,
            ),
            'CreateStaticConsumerGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStaticConsumerGroup,
                    request_deserializer=fumarole__pb2.CreateStaticConsumerGroupRequest.FromString,
                    response_serializer=fumarole__pb2.CreateStaticConsumerGroupResponse.SerializeToString,
            ),
            'Subscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=fumarole__pb2.SubscribeRequest.FromString,
                    response_serializer=geyser__pb2.SubscribeUpdate.SerializeToString,
            ),
            'GetSlotLagInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSlotLagInfo,
                    request_deserializer=fumarole__pb2.GetSlotLagInfoRequest.FromString,
                    response_serializer=fumarole__pb2.GetSlotLagInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fumarole.Fumarole', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fumarole.Fumarole', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Fumarole(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAvailableCommitmentLevels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fumarole.Fumarole/ListAvailableCommitmentLevels',
            fumarole__pb2.ListAvailableCommitmentLevelsRequest.SerializeToString,
            fumarole__pb2.ListAvailableCommitmentLevelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsumerGroupInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fumarole.Fumarole/GetConsumerGroupInfo',
            fumarole__pb2.GetConsumerGroupInfoRequest.SerializeToString,
            fumarole__pb2.ConsumerGroupInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConsumerGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fumarole.Fumarole/ListConsumerGroups',
            fumarole__pb2.ListConsumerGroupsRequest.SerializeToString,
            fumarole__pb2.ListConsumerGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConsumerGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fumarole.Fumarole/DeleteConsumerGroup',
            fumarole__pb2.DeleteConsumerGroupRequest.SerializeToString,
            fumarole__pb2.DeleteConsumerGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateStaticConsumerGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fumarole.Fumarole/CreateStaticConsumerGroup',
            fumarole__pb2.CreateStaticConsumerGroupRequest.SerializeToString,
            fumarole__pb2.CreateStaticConsumerGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fumarole.Fumarole/Subscribe',
            fumarole__pb2.SubscribeRequest.SerializeToString,
            geyser__pb2.SubscribeUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSlotLagInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fumarole.Fumarole/GetSlotLagInfo',
            fumarole__pb2.GetSlotLagInfoRequest.SerializeToString,
            fumarole__pb2.GetSlotLagInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
